include:
  - board: seeeduino_xiao_ble
    shield: orcus_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: orcus-dongle-left
  - board: seeeduino_xiao_ble
    shield: orcus_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: orcus-dongle-right
  - board: seeeduino_xiao_ble
    shield: orcus_dongle dongle_screen
    cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000
    snippet: zmk-usb-logging
    artifact-name: orcus-dongle-screen
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: orcus-settings-reset