include:
  - board: seeeduino_xiao_ble
    shield: orcus_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: orcus_right
 # - board: seeeduino_xiao_ble
 #   shield: settings_reset
