include:
  - board: seeeduino_xiao_ble
    shield: orcus_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: seeeduino_xiao_ble
    shield: orcus_right
 # - board: seeeduino_xiao_ble
 #   shield: settings_reset
